-- First, remove table if it exists 
drop table if exists bookmarks; 

-- Create the table anew
create table bookmarks (
    id INTEGER primary key generated by default as identity,
    title text, 
    body text,  
    rating numeric
);

-- insert some test data 
-- Using a multi-row insert statement here 
insert into bookmarks (title, body, rating)
values
    ('Thinkful', 'The best coding bootcamp in the world', 5),
    ('Google', 'The best search engine on the planet', 5),
    ('Yelp', 'Find the best-worst rated places here', 4),
    ('Leetcode', 'Learn data structures, algos etc.', 3),
    ('Youtube', 'If you like random videos come here', 5),
    ('CrunchyRoll', 'The best anime show are here', 4),
    ('Guitar Center', 'Find instruments here', 3),
    ('GitHub', 'Post all your code or contribute', 5),
    ('HackerOne', 'Join coding competitions', 4),
    ('PluralSight', 'A learning platform for coding', 4);
